import streamlit as st
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import mean_squared_error, accuracy_score
from sklearn.cluster import KMeans
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.decomposition import FactorAnalysis
import io
import plotly.express as px
from fpdf import FPDF
from datetime import datetime

# Set Page Config
st.set_page_config(
    page_title="Astra ML Dashboard",
    page_icon="🌸",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Initialize Session State for Reporting
if 'ml_results' not in st.session_state:
    st.session_state.ml_results = None
if 'task_type' not in st.session_state:
    st.session_state.task_type = None

class PDFReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.set_text_color(199, 21, 133) # Deep Pink
        self.cell(0, 10, 'Astra AI - Premium Analytical Report', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Astra ML Dashboard on {datetime.now().strftime("%Y-%m-%d %H:%M")}', 0, 0, 'C')

    def chapter_title(self, title):
        self.set_font('Arial', 'B', 12)
        self.set_fill_color(255, 240, 245)
        self.set_text_color(199, 21, 133)
        self.cell(0, 10, title, 0, 1, 'L', 1)
        self.ln(4)

    def chapter_body(self, body):
        self.set_font('Arial', '', 10)
        self.set_text_color(0, 0, 0)
        self.multi_cell(0, 7, body)
        self.ln()

# Custom CSS for Premium Glassmorphism Aesthetic
st.markdown("""
<style>
    @import url('https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;700&display=swap');

    /* Global Typography */
    * {
        font-family: 'Outfit', sans-serif;
    }

    /* Main Background */
    .stApp {
        background: radial-gradient(circle at top left, #FFF0F5 0%, #FFB6C1 40%, #E6E6FA 100%);
        color: #4B0082;
    }
    
    /* Glassmorphism Containers */
    [data-testid="stMetric"], .stDataFrame, .stPlotlyChart {
        background: rgba(255, 255, 255, 0.45) !important;
        backdrop-filter: blur(12px) !important;
        border: 1px solid rgba(255, 255, 255, 0.3) !important;
        border-radius: 20px !important;
        padding: 20px !important;
        margin-bottom: 25px !important;
        box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.15) !important;
        transition: transform 0.3s ease;
        overflow: hidden !important;
    }
    
    [data-testid="stMetric"]:hover, .stDataFrame:hover, .stPlotlyChart:hover, .stExpander:hover {
        transform: scale(1.02) translateY(-2px);
        box-shadow: 0 12px 40px 0 rgba(199, 21, 133, 0.25) !important;
        background: rgba(255, 255, 255, 0.55) !important;
        z-index: 10;
    }
    
    /* Sidebar styling */
    section[data-testid="stSidebar"] {
        background: rgba(255, 192, 203, 0.8) !important;
        backdrop-filter: blur(15px);
        border-right: 1px solid rgba(255, 255, 255, 0.3);
    }
    
    /* Headings */
    h1, h2, h3 {
        color: #C71585 !important;
        font-weight: 700 !important;
        letter-spacing: -0.5px;
    }
    
    /* Tabs */
    .stTabs [data-baseweb="tab-list"] {
        gap: 15px;
        background-color: rgba(255, 255, 255, 0.2);
        padding: 12px;
        border-radius: 25px;
        backdrop-filter: blur(5px);
    }
    
    .stTabs [data-baseweb="tab"] {
        height: 55px;
        white-space: pre-wrap;
        background-color: rgba(255, 255, 255, 0.5);
        border-radius: 15px;
        color: #C71585;
        font-weight: 600;
        border: 1px solid rgba(255, 105, 180, 0.2);
        transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
        padding: 0 25px;
    }
    
    .stTabs [aria-selected="true"] {
        background: linear-gradient(135deg, #FF69B4 0%, #C71585 100%) !important;
        color: white !important;
        box-shadow: 0 4px 15px rgba(199, 21, 133, 0.3);
        transform: scale(1.05);
    }
    
    /* Buttons */
    .stButton>button {
        background: linear-gradient(135deg, #FF69B4 0%, #C71585 100%);
        color: white;
        border-radius: 25px;
        border: none;
        padding: 12px 30px;
        font-weight: 600;
        box-shadow: 0 4px 15px rgba(199, 21, 133, 0.2);
        transition: all 0.3s ease;
    }
    
    .stButton>button:hover {
        box-shadow: 0 6px 20px rgba(199, 21, 133, 0.4);
        transform: translateY(-2px);
    }
</style>
""", unsafe_allow_html=True)

# Application Header
st.title("🌸 Astra: Premium ML Dashboard")
st.markdown("---")

# Sidebar - Data Upload and Info
with st.sidebar:
    st.header("📂 Data Management")
    uploaded_file = st.file_uploader("Upload your CSV file", type=["csv"])
    
    if uploaded_file is not None:
        try:
            # Robust File Reading
            uploaded_file.seek(0)
            df = pd.read_csv(uploaded_file, on_bad_lines='skip', engine='python')
            
            # Data Cleaning
            # 1. Drop duplicates
            df.drop_duplicates(inplace=True)
            # 2. Fill numeric nulls with mean
            numeric_cols = df.select_dtypes(include=[np.number]).columns
            df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())
            
            st.success("✅ File loaded successfully!")
            
            st.markdown("### 📊 Dataset Summary")
            st.write(f"**Rows:** {df.shape[0]}")
            st.write(f"**Columns:** {df.shape[1]}")
            
            if st.button("Clear Cache"):
                st.cache_data.clear()
                
            st.divider()
            st.markdown("### 📄 Export & Reports")
            if st.button("Generate Summarized PDF"):
                try:
                    pdf = PDFReport()
                    pdf.add_page()
                    
                    # 1. Dataset Profile
                    pdf.chapter_title('1. Dataset Overview')
                    profile_text = (
                        f"Target File: {uploaded_file.name}\n"
                        f"Process Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}\n"
                        f"Total Observations: {df.shape[0]}\n"
                        f"Total Features: {df.shape[1]}\n"
                        f"Numeric Features: {len(numeric_cols)}\n"
                    )
                    pdf.chapter_body(profile_text)
                    
                    # 2. Statistical Summary
                    pdf.chapter_title('2. Statistical Insights')
                    stats_df = df.describe().transpose()
                    stats_text = ""
                    for index, row in stats_df.iterrows():
                        stats_text += f"{index}: Mean={row['mean']:.2f}, Std={row['std']:.2f}, Min={row['min']:.2f}, Max={row['max']:.2f}\n"
                    pdf.chapter_body(stats_text)
                    
                    # 3. ML Performance
                    if st.session_state.ml_results:
                        pdf.chapter_title('3. Machine Learning Suite Results')
                        pdf.chapter_body(f"Task Type: {st.session_state.task_type}")
                        ml_text = ""
                        for model, score in st.session_state.ml_results.items():
                            ml_text += f"- {model}: {score:.4f}\n"
                        pdf.chapter_body(ml_text)
                        
                        best_model = max(st.session_state.ml_results, key=st.session_state.ml_results.get) if st.session_state.task_type == 'Classification' else min(st.session_state.ml_results, key=st.session_state.ml_results.get)
                        pdf.chapter_title('4. Astra Strategic Recommendation')
                        pdf.chapter_body(f"Based on Accuracy/MSE metrics, the '{best_model}' is the most reliable model for this dataset. We recommend using this model for future predictions on similar data structures.")
                    else:
                        pdf.chapter_title('3. Machine Learning Suite')
                        pdf.chapter_body("Note: No model training results found. Please run the model suite in the 'Model Training' tab to include performance metrics in the report.")

                    # Output PDF
                    pdf_output = pdf.output(dest='S')
                    st.download_button(
                        label="⬇️ Download Astra PDF Report",
                        data=bytes(pdf_output),
                        file_name=f"Astra_Report_{datetime.now().strftime('%Y%m%d_%H%M')}.pdf",
                        mime="application/pdf"
                    )
                except Exception as ex:
                    st.error(f"Error generating PDF: {ex}")
                
        except Exception as e:
            st.error(f"❌ Error loading file: {e}")
            df = None
    else:
        st.info("Please upload a CSV file to begin.")
        df = None

# Main Dashboard Content
if df is not None:
    tab1, tab2, tab3, tab4, tab5, tab6 = st.tabs(["🔍 EDA", "📈 Visualizations", "🤖 Model Training", "✨ 3D PCA", "🏏 Player Corner", "🧪 Advanced Lab"])

    # --- TAB 1: EDA ---
    with tab1:
        st.header("Exploratory Data Analysis")
        
        col1, col2 = st.columns([2, 1], gap="large")
        
        with col1:
            st.subheader("Data Preview")
            st.dataframe(df.head(10), use_container_width=True)
            
        with col2:
            st.subheader("Dataset Statistics")
            st.write(df.describe())

        st.markdown("---")
        st.subheader("Dataset Info")
        buffer = io.StringIO()
        df.info(buf=buffer)
        st.text(buffer.getvalue())

    # --- TAB 2: VISUALIZATIONS ---
    with tab2:
        st.header("Visual Analytics")
        
        # 1. Correlation Heatmap
        st.subheader("Correlation Heatmap")
        if not numeric_cols.empty:
            # Filter out zero variance columns for cleaner heatmap
            corr_df = df[numeric_cols].corr().dropna(how='all', axis=0).dropna(how='all', axis=1)
            
            if not corr_df.empty:
                # Dynamically calculate figsize based on number of columns
                num_vars = len(corr_df.columns)
                fig_size = max(10, num_vars * 0.8)
                
                fig, ax = plt.subplots(figsize=(fig_size, fig_size * 0.7))
                
                # Create mask for upper triangle
                mask = np.triu(np.ones_like(corr_df, dtype=bool))
                
                # Enhanced Heatmap
                sns.heatmap(
                    corr_df, 
                    mask=mask,
                    annot=True, 
                    cmap="RdPu", 
                    fmt=".2f", 
                    ax=ax,
                    annot_kws={"size": 10 if num_vars < 10 else 7},
                    cbar_kws={"shrink": .8},
                    square=True,
                    linewidths=.5
                )
                
                plt.xticks(rotation=45, ha='right')
                plt.yticks(rotation=0)
                ax.set_title("Feature Correlation Matrix", fontsize=16, pad=20, color="#C71585")
                fig.tight_layout()
                st.pyplot(fig)
            else:
                st.warning("Not enough variance in numeric columns to generate a correlation map.")
        else:
            st.warning("No numeric columns available for correlation.")

        st.markdown("---")
        
        # 2. Distribution & Comparison
        col_vis1, col_vis2 = st.columns(2, gap="large")
        
        with col_vis1:
            st.subheader("Histogram")
            hist_col = st.selectbox("Select column for Histogram", numeric_cols)
            if hist_col:
                fig_hist, ax_hist = plt.subplots()
                sns.histplot(df[hist_col], kde=True, color="#C71585", ax=ax_hist)
                st.pyplot(fig_hist)
                
        with col_vis2:
            st.subheader("Boxplot")
            box_col = st.selectbox("Select column for Boxplot", numeric_cols)
            if box_col:
                fig_box, ax_box = plt.subplots()
                sns.boxplot(y=df[box_col], color="#FFB6C1", ax=ax_box)
                st.pyplot(fig_box)

        st.markdown("---")
        
        # 3. Scatter Plot
        st.subheader("Scatter Plot Analysis")
        col_scat1, col_scat2 = st.columns(2, gap="large")
        with col_scat1:
            scat_x = st.selectbox("X Axis", numeric_cols, index=0)
        with col_scat2:
            scat_y = st.selectbox("Y Axis", numeric_cols, index=min(1, len(numeric_cols)-1))
            
        fig_scat, ax_scat = plt.subplots()
        sns.scatterplot(data=df, x=scat_x, y=scat_y, color="#FF1493", alpha=0.6, ax=ax_scat)
        st.pyplot(fig_scat)

    # --- TAB 3: MODEL TRAINING ---
    with tab3:
        st.header("🤖 Advanced Machine Learning Lab")
        st.markdown("Configure, train, and compare multiple models to find the best performer for your data.")
        
        if len(numeric_cols) < 2:
            st.error("Need at least 2 numeric columns for training.")
        else:
            ml_col1, ml_col2 = st.columns([1, 2], gap="large")
            
            with ml_col1:
                st.subheader("⚙️ Model Configuration")
                target_col = st.selectbox("Select Target Variable", numeric_cols, key="target_sel")
                feature_mode = st.radio("Feature Set", ["All Raw Features", "PCA Components (Top 3)"])
                
                st.divider()
                st.markdown("#### 🛠️ Hyperparameters")
                dt_depth = st.slider("Decision Tree Max Depth", 1, 20, 5)
                rf_estimators = st.slider("Random Forest Estimators", 10, 200, 100)
                rf_depth = st.slider("Random Forest Max Depth", 1, 20, 10)
                test_size = st.slider("Test Set Size", 0.1, 0.4, 0.2)
                
            with ml_col2:
                # Data Preparation
                X = df[numeric_cols].drop(columns=[target_col])
                y = df[target_col]
                is_classification = y.nunique() < 10 or y.dtype == 'object'
                st.info(f"**Task Detected:** {'Classification' if is_classification else 'Regression'}")
                
                # Split & Scale
                X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=42)
                scaler = StandardScaler()
                X_train_scaled = scaler.fit_transform(X_train)
                X_test_scaled = scaler.transform(X_test)
                
                if feature_mode == "PCA Components (Top 3)":
                    pca_ml = PCA(n_components=min(3, X.shape[1]))
                    X_train_final = pca_ml.fit_transform(X_train_scaled)
                    X_test_final = pca_ml.transform(X_test_scaled)
                    feature_names = [f"PC{i+1}" for i in range(X_train_final.shape[1])]
                else:
                    X_train_final = X_train_scaled
                    X_test_final = X_test_scaled
                    feature_names = X.columns.tolist()

                if st.button("🚀 Execute Astra Model Suite", use_container_width=True):
                    with st.spinner("✨ Training models and generating insights..."):
                        results = {}
                        trained_models = {}
                        y_train_ml = y_train.astype(int) if is_classification else y_train
                        y_test_ml = y_test.astype(int) if is_classification else y_test
                        
                        # Logistic/Linear
                        if is_classification:
                            model = LogisticRegression(max_iter=1000)
                            model.fit(X_train_final, y_train_ml)
                            results['Logistic Regression'] = accuracy_score(y_test_ml, model.predict(X_test_final))
                        else:
                            model = LinearRegression()
                            model.fit(X_train_final, y_train_ml)
                            results['Linear Regression'] = mean_squared_error(y_test_ml, model.predict(X_test_final))
                        trained_models['Base Model'] = model

                        # Decision Tree
                        dt = DecisionTreeClassifier(max_depth=dt_depth) if is_classification else DecisionTreeRegressor(max_depth=dt_depth)
                        dt.fit(X_train_final, y_train_ml)
                        results['Decision Tree'] = accuracy_score(y_test_ml, dt.predict(X_test_final)) if is_classification else mean_squared_error(y_test_ml, dt.predict(X_test_final))
                        trained_models['Decision Tree'] = dt

                        # Random Forest
                        rf = RandomForestClassifier(n_estimators=rf_estimators, max_depth=rf_depth) if is_classification else RandomForestRegressor(n_estimators=rf_estimators, max_depth=rf_depth)
                        rf.fit(X_train_final, y_train_ml)
                        results['Random Forest'] = accuracy_score(y_test_ml, rf.predict(X_test_final)) if is_classification else mean_squared_error(y_test_ml, rf.predict(X_test_final))
                        trained_models['Random Forest'] = rf

                        # UI Metrics & Charts
                        st.session_state.ml_results = results
                        st.session_state.task_type = 'Classification' if is_classification else 'Regression'
                        
                        st.success("🎉 Astra Model Suite Execution Complete!")
                        res_tab1, res_tab2 = st.tabs(["📊 Performance Metrics", "🔍 Feature Importance"])
                        
                        with res_tab1:
                            metric_name = "Accuracy" if is_classification else "MSE"
                            plot_df = pd.DataFrame(list(results.items()), columns=['Model', 'Score'])
                            fig_comp = px.bar(plot_df, x='Model', y='Score', color='Score', 
                                            title=f"Comparison ({metric_name})", template="plotly_white", 
                                            color_continuous_scale="RdPu")
                            st.plotly_chart(fig_comp, use_container_width=True)
                            
                            m_cols = st.columns(len(results))
                            for idx, (m_name, m_score) in enumerate(results.items()):
                                m_cols[idx].metric(m_name, f"{m_score:.4f}")

                        with res_tab2:
                            if feature_mode == "All Raw Features":
                                imp = trained_models['Random Forest'].feature_importances_
                                feat_df = pd.DataFrame({'Feature': feature_names, 'Importance': imp}).sort_values('Importance')
                                fig_feat = px.bar(feat_df, x='Importance', y='Feature', orientation='h', 
                                                title="Feature Importance (RF)", color='Importance', 
                                                color_continuous_scale="RdPu")
                                st.plotly_chart(fig_feat, use_container_width=True)
                            else:
                                st.warning("Feature importance is best viewed with 'All Raw Features'.")

    # --- TAB 4: 3D PCA ---
    with tab4:
        st.header("✨ Interactive 3D PCA")
        st.markdown("Explore your data in 3D. Hover over points for details and use the toolbar to zoom and rotate.")
        
        if len(numeric_cols) < 3:
            st.warning("Need at least 3 numeric columns for 3D PCA.")
        else:
            col_pca1, col_pca2 = st.columns([1, 3])
            
            with col_pca1:
                st.subheader("⚙️ Settings")
                pca_features = st.multiselect(
                    "Select Features for PCA", 
                    numeric_cols.tolist(), 
                    default=numeric_cols.tolist()
                )
                
                color_col = st.selectbox(
                    "Color by Column", 
                    [None] + df.columns.tolist(),
                    index=len(df.columns) if "Species" in df.columns or "target" in df.columns else 0
                )
                
                size_col = st.selectbox(
                    "Size by Column", 
                    [None] + numeric_cols.tolist()
                )

            with col_pca2:
                if len(pca_features) >= 3:
                    # Scaling
                    scaler_pca = StandardScaler()
                    X_pca_input = scaler_pca.fit_transform(df[pca_features].fillna(0))
                    
                    # PCA
                    pca_3d = PCA(n_components=3)
                    components = pca_3d.fit_transform(X_pca_input)
                    
                    # Create DF for Plotly
                    pca_df = pd.DataFrame(
                        data=components, 
                        columns=['PC1', 'PC2', 'PC3']
                    )
                    
                    # Add back original data for hover/color
                    for col in df.columns:
                        pca_df[col] = df[col].values
                        
                    # Create 3D Scatter Plot
                    fig_3d = px.scatter_3d(
                        pca_df, x='PC1', y='PC2', z='PC3',
                        color=color_col if color_col else None,
                        size=size_col if size_col else None,
                        hover_data=df.columns.tolist(),
                        template="plotly_dark",
                        color_continuous_scale=px.colors.sequential.RdPu,
                        color_discrete_sequence=px.colors.qualitative.Pastel
                    )
                    
                    fig_3d.update_layout(
                        margin=dict(l=0, r=0, b=0, t=40),
                        scene=dict(
                            xaxis_title='PC1',
                            yaxis_title='PC2',
                            zaxis_title='PC3',
                            bgcolor='rgba(0,0,0,0)'
                        ),
                        paper_bgcolor='rgba(0,0,0,0)',
                        font=dict(color="#C71585")
                    )
                    
                    st.plotly_chart(fig_3d, use_container_width=True)
                    
                    # Variance info
                    total_var = pca_3d.explained_variance_ratio_.sum() * 100
                    st.info(f"💡 The 3 principal components explain **{total_var:.2f}%** of the total variance.")
                else:
                    st.error("Please select at least 3 features.")

    # --- TAB 5: PLAYER CORNER ---
    with tab5:
        st.header("🏏 Player Improvement Corner")
        st.markdown("Deep-dive into individual player performance. Optimized for IPL 2025 and ball-by-ball datasets.")
        
        # Detect player columns with broader scope
        player_cols = [c for c in df.columns if any(x in c.lower() for x in ['striker', 'batter', 'bowler', 'player', 'name'])]
        
        if not player_cols:
            st.warning("Could not automatically detect player columns. Please check your dataset headers.")
        else:
            p_col1, p_col2 = st.columns([1, 2], gap="large")
            
            with p_col1:
                st.subheader("👤 Select Player")
                selected_col = st.selectbox("Role / Column", player_cols)
                all_players = sorted(df[selected_col].unique().tolist())
                selected_player = st.selectbox("Player Name", all_players)
                
                # Filter data
                player_df = df[df[selected_col] == selected_player]
                
                # SENSOR: Robust Metric Mapping
                is_batting_file = any(x in df.columns for x in ['Runs', 'runs_off_bat', 'BF'])
                is_bowling_file = any(x in df.columns for x in ['WKT', 'WKTs', 'ECO', 'wicket_type'])
                
                # Initialize variables
                runs, balls, sr, fours, sixes = 0, 0, 0, 0, 0
                wickets, economy, avg, matches = 0, 0, 0, 0

                # BATTING CALCULATION
                if is_batting_file:
                    # Support for Aggregate (IPL) vs Ball-by-Ball
                    if 'Runs' in df.columns: # IPL Batters
                        runs = player_df['Runs'].iloc[0]
                        balls = player_df['BF'].iloc[0]
                        sr = player_df['SR'].iloc[0]
                        fours = player_df['4s'].iloc[0]
                        sixes = player_df['6s'].iloc[0]
                        avg = player_df['AVG'].iloc[0] if 'AVG' in df.columns else 0
                    else: # Ball-by-ball
                        runs = player_df['runs_off_bat'].sum() if 'runs_off_bat' in df.columns else 0
                        balls = len(player_df)
                        sr = (runs / balls * 100) if balls > 0 else 0
                        fours = len(player_df[player_df['runs_off_bat'] == 4]) if 'runs_off_bat' in df.columns else 0
                        sixes = len(player_df[player_df['runs_off_bat'] == 6]) if 'runs_off_bat' in df.columns else 0
                
                # BOWLING CALCULATION
                elif is_bowling_file:
                    if 'WKT' in df.columns: # IPL Bowlers
                        wickets = player_df['WKT'].iloc[0]
                        economy = player_df['ECO'].iloc[0]
                        sr = player_df['SR'].iloc[0]
                        avg = player_df['AVG'].iloc[0] if 'AVG' in df.columns else 0
                        balls_bowled = float(player_df['OVR'].iloc[0]) * 6 if 'OVR' in df.columns else 0
                    else: # Ball-by-ball
                        wickets = len(player_df[player_df['wicket_type'].notna()]) if 'wicket_type' in df.columns else 0
                        runs_conceded = player_df['runs_off_bat'].sum() + player_df['extras'].sum() if 'runs_off_bat' in df.columns else 0
                        balls_bowled = len(player_df)
                        economy = (runs_conceded / (balls_bowled / 6)) if balls_bowled > 0 else 0

                st.divider()
                if st.button("✨ Capture Player Profile for PDF"):
                    report_data = {
                        'name': selected_player,
                        'role': 'Batter' if is_batting_file else 'Bowler',
                        'runs': runs, 'sr': sr, 'fours': fours, 'sixes': sixes, 'avg': avg,
                        'wickets': wickets, 'economy': economy
                    }
                    st.session_state.player_report = report_data
                    st.success("Analysis Captured! See Preview Below.")

            with p_col2:
                # Performance Dashboard
                st.subheader(f"{selected_player} Metrics")
                m1, m2, m3, m4 = st.columns(4)
                
                if is_batting_file:
                    m1.metric("Total Runs", runs)
                    m2.metric("Strike Rate", sr)
                    m3.metric("Boundaries (4s/6s)", f"{fours}/{sixes}")
                    m4.metric("Batting Average", avg)
                else:
                    m1.metric("Wickets", wickets)
                    m2.metric("Economy", economy)
                    m3.metric("Avg / SR", f"{avg}/{sr}")
                    m4.metric("Role", "Bowler")

                # RE-ADDED PREVIEW PER USER REQUEST
                if 'player_report' in st.session_state and st.session_state.player_report['name'] == selected_player:
                    st.markdown("---")
                    st.subheader("🔍 Report Summary Preview")
                    with st.container():
                        st.markdown(f"""
                        <div style="background: rgba(255,255,255,0.7); padding: 20px; border-radius: 15px; border: 1px solid #C71585;">
                            <h4 style="color: #C71585; margin: 0;">PREVIEW: Astra Player Report</h4>
                            <p><b>Player:</b> {selected_player}</p>
                            <p><b>Role:</b> {st.session_state.player_report['role']}</p>
                            <hr>
                            <p><b>Executive Summary:</b> {selected_player} has shown significant impact in current fixtures. 
                                {f'Total Runs: {runs} | SR: {sr}' if is_batting_file else f'Total Wickets: {wickets} | Economy: {economy}'} 
                                suggests a key role in the team performance.</p>
                        </div>
                        """, unsafe_allow_html=True)
                        
                        # PDF generation
                        p_pdf = PDFReport()
                        p_pdf.add_page()
                        p_pdf.chapter_title(f"Astra Deep-Dive: {selected_player}")
                        p_text = f"Role: {st.session_state.player_report['role']}\n"
                        if is_batting_file:
                            p_text += f"Total Runs: {runs}\nStrike Rate: {sr}\nAverage: {avg}\n4s/6s: {fours}/{sixes}"
                        else:
                            p_text += f"Wickets: {wickets}\nEconomy: {economy}\nBowling SR: {sr}\nRole: {p_report['role']}"
                        p_pdf.chapter_body(p_text)
                        
                        p_pdf_output = p_pdf.output(dest='S')
                        st.download_button(
                            label=f"⬇️ Download {selected_player}'s Full PDF Report",
                            data=bytes(p_pdf_output),
                            file_name=f"Astra_Player_{selected_player}.pdf",
                            mime="application/pdf",
                            key="player_dl_final"
                        )
                else:
                    st.info("💡 Click 'Capture Player Profile' to see a preview and generate your PDF report.")

                # Charts
                if is_batting_file and 'Runs' not in df.columns: # Line chart only for ball-by-ball
                    match_stats = player_df.groupby('match_id')['runs_off_bat'].sum().reset_index()
                    st.plotly_chart(px.line(match_stats, x='match_id', y='runs_off_bat', title="Runs Trend"), use_container_width=True)
                elif is_batting_file:
                    st.plotly_chart(px.bar(player_df, x='Team', y=['4s', '6s'], barmode='group', title="Boundary Profile"), use_container_width=True)

    # --- TAB 6: ADVANCED LAB ---
    with tab6:
        st.header("🧪 Advanced Analytics Lab")
        st.markdown("Unlock deeper statistical insights using Clustering, LDA, and Factor Analysis.")
        
        adv_subtab1, adv_subtab2, adv_subtab3 = st.tabs(["🧩 K-Means Clustering", "🎯 LDA", "🔍 Factor Analysis"])
        
        with adv_subtab1:
            st.subheader("K-Means Clustering")
            st.info("Group players or matches based on similarity in numeric features.")
            
            c_cols = st.multiselect("Select Features for Clustering", numeric_cols, default=numeric_cols[:2])
            if len(c_cols) >= 2:
                k_val = st.slider("Select Number of Clusters (K)", 2, 8, 3)
                
                # Model
                X_clust = df[c_cols].fillna(df[c_cols].mean())
                kmeans = KMeans(n_clusters=k_val, random_state=42)
                df['Cluster'] = kmeans.fit_predict(X_clust)
                
                fig_clust = px.scatter(df, x=c_cols[0], y=c_cols[1], color='Cluster',
                                      hover_name=player_cols[0] if player_cols else None,
                                      title=f"K-Means Clustering (K={k_val})",
                                      color_continuous_scale='Portland')
                st.plotly_chart(fig_clust, use_container_width=True)
                st.success(f"Successfully identified {k_val} distinct clusters in your data.")
            else:
                st.warning("Please select at least 2 features to start clustering.")

        with adv_subtab2:
            st.subheader("Linear Discriminant Analysis (LDA)")
            st.info("Supervised dimensionality reduction: Find features that separate categories (e.g., Teams).")
            
            cat_cols = df.select_dtypes(include=['object']).columns.tolist()
            if cat_cols:
                lda_feat = st.multiselect("Select Features for LDA", numeric_cols, default=numeric_cols[:3], key="lda_f")
                lda_target = st.selectbox("Select Target Column", cat_cols if cat_cols else ["No Categorical Data Found"])
                
                if len(lda_feat) >= 2 and lda_target != "No Categorical Data Found":
                    try:
                        X_lda = df[lda_feat].fillna(df[lda_feat].mean())
                        y_lda = df[lda_target]
                        
                        # LDA Safety Check: n_samples > n_classes
                        if len(y_lda) <= len(y_lda.unique()):
                            st.warning("⚠️ **LDA Notice:** Too many unique values in the target column relative to data size. Please choose a column with fewer categories (e.g., Team).")
                        else:
                            lda = LinearDiscriminantAnalysis(n_components=min(len(lda_feat), len(y_lda.unique())-1, 2))
                            X_lda_transformed = lda.fit_transform(X_lda, y_lda)
                            
                            lda_df = pd.DataFrame(X_lda_transformed, columns=[f'LD{i+1}' for i in range(X_lda_transformed.shape[1])])
                            lda_df[lda_target] = y_lda.values
                            
                            fig_lda = px.scatter(lda_df, x='LD1', y='LD2' if X_lda_transformed.shape[1] > 1 else 'LD1', 
                                                 color=lda_target, title=f"LDA Projection: Separating by {lda_target}",
                                                 color_discrete_sequence=px.colors.qualitative.Prism)
                            st.plotly_chart(fig_lda, use_container_width=True)
                    except Exception as ex:
                        st.error(f"❌ Statistical Error: {ex}. Please simplify your feature selection.")
                else:
                    st.warning("Select at least 2 features and a categorical target.")
            else:
                st.error("LDA requires a categorical column (e.g., Team, Wicket Type) to serve as a target.")

        with adv_subtab3:
            st.subheader("Factor Analysis")
            st.info("Discover latent variables that represent your data better than raw features.")
            
            fa_cols = st.multiselect("Select Features for Factor Analysis", numeric_cols, default=numeric_cols[:4], key="fa_f")
            if len(fa_cols) >= 3:
                n_fact = st.slider("Select Number of Factors", 2, len(fa_cols), 2)
                
                fa = FactorAnalysis(n_components=n_fact, random_state=42)
                X_fa = df[fa_cols].fillna(df[fa_cols].mean())
                X_fa_transformed = fa.fit_transform(X_fa)
                
                fa_df = pd.DataFrame(X_fa_transformed, columns=[f'Factor {i+1}' for i in range(n_fact)])
                if player_cols: fa_df['Player'] = df[player_cols[0]].values
                
                fig_fa = px.scatter(fa_df, x='Factor 1', y='Factor 2', hover_name='Player' if player_cols else None,
                                    title="Factor Analysis - Latent Space Projection",
                                    color_discrete_sequence=['#FF1493'])
                st.plotly_chart(fig_fa, use_container_width=True)
            else:
                st.warning("Select at least 3 features for Factor Analysis.")

else:
    # Landing Page if no file is uploaded
    st.markdown("""
    <div style="text-align: center; padding: 50px;">
        <h2 style="color: #FF1493;">Welcome to Astra ML Dashboard!</h2>
        <p style="font-size: 1.2rem; color: #4B0082;">Please upload a CSV file in the sidebar to unlock data magic. ✨</p>
        <img src="https://img.icons8.com/bubbles/200/000000/artificial-intelligence.png"/>
    </div>
    """, unsafe_allow_html=True)
