"""
DAVL — Report Export Module
Download processed data, plots, and analysis reports.
"""

import pandas as pd
import io
import json
from datetime import datetime


def export_dataframe_csv(df: pd.DataFrame) -> bytes:
    """Export DataFrame as CSV bytes for download."""
    buffer = io.StringIO()
    df.to_csv(buffer, index=False)
    return buffer.getvalue().encode("utf-8")


def export_dataframe_excel(df: pd.DataFrame) -> bytes:
    """Export DataFrame as Excel bytes for download."""
    buffer = io.BytesIO()
    df.to_excel(buffer, index=False, engine="openpyxl")
    return buffer.getvalue()


def generate_analysis_report(
    df: pd.DataFrame,
    overview: dict,
    quality_summary: dict,
    insights: dict,
    target_col: str = None,
) -> str:
    """Generate a comprehensive Markdown analysis report."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    report = f"""# 📊 DAVL — Dataset Analysis Report
**Generated:** {timestamp}

---

## 1. Dataset Overview

| Metric | Value |
|--------|-------|
| Rows | {overview.get('rows', 'N/A'):,} |
| Columns | {overview.get('columns', 'N/A')} |
| Numeric Columns | {overview.get('num_numeric', 0)} |
| Categorical Columns | {overview.get('num_categorical', 0)} |
| Memory Usage | {overview.get('memory_usage', 'N/A')} |
| Missing Values | {overview.get('missing_total', 0):,} |
| Duplicate Rows | {overview.get('duplicate_rows', 0):,} |
| Target Column | {target_col or 'Not detected'} |

### Column Types
"""
    for dtype, count in overview.get("dtypes_summary", {}).items():
        report += f"- **{dtype}**: {count} columns\n"

    # Data Quality Section
    report += "\n---\n\n## 2. Data Quality\n\n"

    missing_df = quality_summary.get("missing_values", pd.DataFrame())
    if isinstance(missing_df, pd.DataFrame) and not missing_df.empty:
        cols_with_missing = missing_df[missing_df["Missing Count"] > 0]
        if not cols_with_missing.empty:
            report += "### Missing Values\n\n"
            report += "| Column | Missing Count | Missing % |\n"
            report += "|--------|--------------|----------|\n"
            for _, row in cols_with_missing.iterrows():
                report += f"| {row['Column']} | {row['Missing Count']} | {row['Missing %']}% |\n"
            report += "\n"
        else:
            report += "✅ No missing values.\n\n"

    dup_info = quality_summary.get("duplicates", {})
    dup_count = dup_info.get("duplicate_count", 0)
    report += f"### Duplicates\n- **{dup_count}** duplicate rows "
    report += f"({dup_info.get('duplicate_percentage', 0)}% of data)\n\n"

    const_cols = quality_summary.get("constant_columns", [])
    if const_cols:
        report += f"### Constant Columns\n- {', '.join(const_cols)}\n\n"

    # Insights Section
    report += "---\n\n## 3. Analyst Insights\n\n"
    sections_map = {
        "key_observations": "### Key Observations",
        "important_features": "### Important Features",
        "correlations": "### Correlation Insights",
        "redundant_columns": "### Redundant Columns",
        "data_quality": "### Data Quality Issues",
        "preprocessing_suggestions": "### Preprocessing Suggestions",
    }

    for key, title in sections_map.items():
        items = insights.get(key, [])
        if items:
            report += f"{title}\n\n"
            for item in items:
                report += f"- {item}\n"
            report += "\n"

    # Descriptive Stats
    numeric_df = df.select_dtypes("number")
    if not numeric_df.empty:
        report += "---\n\n## 4. Descriptive Statistics\n\n"
        stats = numeric_df.describe().round(4).T
        report += stats.to_markdown() + "\n\n"

    report += f"\n---\n*Report generated by DAVL — Data Analysis & Visualization Lab*\n"
    return report


def export_insights_json(insights: dict) -> str:
    """Export insights as JSON string."""
    return json.dumps(insights, indent=2, default=str)
